import React, { useEffect, useMemo, useState } from 'react';
import {
  ActivityIndicator,
  Pressable,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation/types';
import { ScreenBackground } from '../components/ScreenBackground';
import { SectionCard } from '../components/SectionCard';
import { PrimaryButton } from '../components/PrimaryButton';
import { Badge } from '../components/Badge';
import { MetricGauge } from '../components/MetricGauge';
import { StatTile } from '../components/StatTile';
import { StageStepper } from '../components/StageStepper';
import { MoatRowEditor } from '../components/MoatRowEditor';
import { FlagCard } from '../components/FlagCard';
import { ValueBar } from '../components/ValueBar';
import { DonutRing } from '../components/DonutRing';
import { SegmentedPicker } from '../components/SegmentedPicker';
import { colors, fonts, radius, spacing } from '../theme/theme';
import { useAppState } from '../context/AppStateContext';
import { useTickerReport } from '../hooks/useTickerReport';
import {
  METRICS,
  gradeMetric,
  gaugeFraction,
  thresholdFraction,
  grahamIntrinsicValue,
  marginOfSafetyPrice,
  buildFlags,
  buildAutoThesis,
  qualityLabel,
  priceLabel,
} from '../services/playbook';
import { Assessment, loadAssessment, saveAssessment } from '../services/reportStorage';
import { formatCompactUsd, formatPct, formatUsd, formatX } from '../utils/format';

type Props = NativeStackScreenProps<RootStackParamList, 'Report'>;

const RATINGS = ['BUY', 'HOLD', 'SELL'] as const;

export default function ReportScreen({ route, navigation }: Props) {
  const { symbol } = route.params;
  const { apiKey, aaaYieldPct, pushRecentTicker } = useAppState();
  const { loading, error, data, run } = useTickerReport(symbol, apiKey);
  const [assessment, setAssessment] = useState<Assessment | null>(null);

  useEffect(() => {
    run();
    pushRecentTicker(symbol);
    loadAssessment(symbol).then(setAssessment);
  }, [symbol]);

  const updateAssessment = (patch: Partial<Assessment>) => {
    setAssessment((prev) => {
      const next = { ...(prev as Assessment), ...patch };
      saveAssessment(symbol, next);
      return next;
    });
  };

  const graham = useMemo(() => {
    if (!data) return null;
    const eps = data.eps > 0 ? data.eps : null;
    if (!eps) return null;
    const base = grahamIntrinsicValue({ eps, growthRatePct: data.epsGrowthRatePct, aaaYieldPct });
    const conservative = grahamIntrinsicValue({ eps, growthRatePct: Math.max(0, data.epsGrowthRatePct - 4), aaaYieldPct });
    const optimistic = grahamIntrinsicValue({ eps, growthRatePct: data.epsGrowthRatePct + 4, aaaYieldPct });
    const mos = marginOfSafetyPrice(base);
    return { base, conservative, optimistic, mos, priceVsIntrinsic: base > 0 ? data.price / base : null };
  }, [data, aaaYieldPct]);

  const flags = useMemo(() => {
    if (!data) return [];
    return buildFlags({
      peRatio: data.peRatio,
      debtToEquity: data.debtToEquity,
      currentRatio: data.currentRatio,
      operatingCashFlow: data.operatingCashFlow,
      netIncome: data.netIncomeTTM,
      freeCashFlow: data.freeCashFlow,
      dividendYield: data.dividendYield,
    });
  }, [data]);

  const thesis = useMemo(() => {
    if (!data) return { bull: [], bear: [] };
    return buildAutoThesis({
      grossMargin: data.grossMargin,
      netMargin: data.netMargin,
      roe: data.roe,
      roic: data.roic,
      currentRatio: data.currentRatio,
      debtToEquity: data.debtToEquity,
      peRatio: data.peRatio,
      dividendYield: data.dividendYield,
      priceVsIntrinsic: graham?.priceVsIntrinsic ?? null,
    });
  }, [data, graham]);

  const onShare = async () => {
    if (!data || !assessment) return;
    const lines = [
      `${data.companyName} (${data.symbol}) — Ticker Report`,
      `Price ${formatUsd(data.price)} · Mkt Cap ${formatCompactUsd(data.marketCap)} · Rating ${assessment.rating}`,
      `Gross Margin ${formatPct(data.grossMargin)} · Net Margin ${formatPct(data.netMargin)} · ROE ${formatPct(data.roe)}`,
      `Current Ratio ${formatX(data.currentRatio)} · Debt/Equity ${formatX(data.debtToEquity)} · P/E ${formatX(data.peRatio)}`,
      graham ? `Graham V ~${formatUsd(graham.base)} · Margin-of-safety buy ~${formatUsd(graham.mos)}` : '',
      assessment.headline ? `Thesis: ${assessment.headline}` : '',
      'Generated by Ticker Report, per The Investing Playbook. Not investment advice.',
    ].filter(Boolean);
    try {
      await Share.share({ message: lines.join('\n') });
    } catch {
      // user cancelled — no-op
    }
  };

  const rangeFraction = data && data.yearHigh > data.yearLow ? (data.price - data.yearLow) / (data.yearHigh - data.yearLow) : 0.5;
  const quality = data ? qualityLabel(data.netMargin, data.roe) : 'UNRATED';
  const priceTag = graham ? priceLabel(graham.priceVsIntrinsic) : 'UNRATED';
  const moatHeadline = assessment?.moatRows.find((r) => r.width === 'Wide')
    ? 'WIDE'
    : assessment?.moatRows.some((r) => r.width === 'Narrow')
    ? 'NARROW'
    : 'NONE';

  const fitScore = useMemo(() => {
    if (!data) return null;
    let passing = 0;
    let counted = 0;
    for (const def of METRICS) {
      const value = (data as any)[def.key] as number | null;
      const grade = gradeMetric(def.key, value);
      if (grade === 'N/A') continue;
      counted += 1;
      if (grade === 'PASS' || grade === 'STRONG' || grade === 'OK') passing += 1;
    }
    return counted > 0 ? passing / counted : null;
  }, [data]);

  return (
    <ScreenBackground>
      <SafeAreaView style={{ flex: 1 }} edges={['top', 'left', 'right']}>
        <View style={styles.navRow}>
          <Pressable onPress={() => navigation.goBack()} style={styles.backBtn}>
            <Text style={styles.backText}>‹</Text>
          </Pressable>
          <Text style={styles.navTitle}>{symbol}</Text>
          <Pressable onPress={onShare} disabled={!data} style={styles.backBtn}>
            <Text style={[styles.backText, { fontSize: 16 }]}>⇪</Text>
          </Pressable>
        </View>

        <ScrollView contentContainerStyle={styles.scroll}>
          {loading && (
            <View style={styles.centerBox}>
              <ActivityIndicator color={colors.teal} size="large" />
              <Text style={styles.loadingText}>Pulling {symbol} against the Playbook…</Text>
            </View>
          )}

          {!loading && error && (
            <View style={styles.centerBox}>
              <Text style={styles.errorTitle}>Couldn't build this report</Text>
              <Text style={styles.errorBody}>{error}</Text>
              <PrimaryButton label="RETRY" onPress={run} style={{ marginTop: spacing(4), alignSelf: 'stretch' }} />
              <PrimaryButton
                label="OPEN SETTINGS"
                variant="ghost"
                onPress={() => navigation.navigate('Settings')}
                style={{ marginTop: spacing(3), alignSelf: 'stretch' }}
              />
            </View>
          )}

          {!loading && !error && data && assessment && (
            <>
              {/* COVER */}
              <View style={styles.cover}>
                <Text style={styles.eyebrow}>EQUITY RESEARCH BRIEF · PREPARED PER THE INVESTING PLAYBOOK</Text>
                <Text style={styles.companyName}>{data.companyName}</Text>
                <View style={styles.tickerRow}>
                  <Badge label={`${data.exchange || 'NASDAQ'} : ${data.symbol}`} tone="teal" />
                  <Badge label={data.sector || 'SECTOR N/A'} />
                </View>

                <View style={styles.priceRow}>
                  <View>
                    <Text style={styles.price}>{formatUsd(data.price)}</Text>
                    <Text style={[styles.changePct, { color: data.changePercent >= 0 ? colors.pass : colors.fail }]}>
                      {data.changePercent >= 0 ? '▲' : '▼'} {Math.abs(data.changePercent).toFixed(2)}%
                    </Text>
                  </View>
                  {fitScore !== null && (
                    <DonutRing
                      size={78}
                      strokeWidth={8}
                      fraction={fitScore}
                      label={`${Math.round(fitScore * 100)}%`}
                      sublabel="PLAYBOOK FIT"
                    />
                  )}
                  <View style={{ alignItems: 'flex-end' }}>
                    <Text style={styles.mktCapLabel}>MKT CAP</Text>
                    <Text style={styles.mktCapValue}>{formatCompactUsd(data.marketCap)}</Text>
                  </View>
                </View>

                <View style={styles.rangeWrap}>
                  <View style={styles.rangeTrack}>
                    <View style={[styles.rangeDot, { left: `${Math.max(2, Math.min(98, rangeFraction * 100))}%` }]} />
                  </View>
                  <View style={styles.rangeLabels}>
                    <Text style={styles.rangeText}>52W LOW {formatUsd(data.yearLow)}</Text>
                    <Text style={styles.rangeText}>52W HIGH {formatUsd(data.yearHigh)}</Text>
                  </View>
                </View>

                <View style={styles.ratingBlock}>
                  <Text style={styles.fieldLabel}>YOUR RATING</Text>
                  <SegmentedPicker options={RATINGS} value={assessment.rating} onChange={(rating) => updateAssessment({ rating })} />
                </View>
              </View>

              {/* VITAL SIGNS */}
              <SectionCard eyebrow="Ref.B — Vital Signs" title="Company Snapshot">
                <View style={styles.tileGrid}>
                  <StatTile label="SECTOR" value={data.sector || '—'} />
                  <StatTile label="INDUSTRY" value={data.industry || '—'} />
                  <StatTile label="EMPLOYEES" value={data.employees ? Number(data.employees).toLocaleString() : '—'} />
                  <StatTile label="HQ" value={[data.city, data.state || data.country].filter(Boolean).join(', ') || '—'} />
                  <StatTile label="DIVIDEND YIELD" value={formatPct(data.dividendYield)} accent />
                  <StatTile label="BETA" value={data.beta !== null ? data.beta.toFixed(2) : '—'} />
                </View>
              </SectionCard>

              {/* BUSINESS PROFILE */}
              <SectionCard eyebrow="Fig.01 — Business Profile" title="What Does This Company Do?">
                <Text style={styles.paragraph}>{data.description || 'No description available from the data provider.'}</Text>
              </SectionCard>

              {/* LIFECYCLE */}
              <SectionCard eyebrow="Playbook §7" title="Business Life Cycle">
                <StageStepper stageId={assessment.stageId} onChange={(stageId) => updateAssessment({ stageId })} />
              </SectionCard>

              {/* MOAT */}
              <SectionCard eyebrow="Playbook §6" title="Moat Assessment">
                <Text style={styles.helperText}>Source · current width · direction — score each candidate advantage.</Text>
                {assessment.moatRows.map((row, i) => (
                  <MoatRowEditor
                    key={i}
                    row={row}
                    onChange={(next) => {
                      const rows = [...assessment.moatRows];
                      rows[i] = next;
                      updateAssessment({ moatRows: rows });
                    }}
                  />
                ))}
              </SectionCard>

              {/* SCORECARD */}
              <SectionCard eyebrow="Playbook §2-3" title="The Scorecard">
                <Text style={styles.helperText}>Filled bar = reading · tick = Playbook target.</Text>
                {METRICS.map((def, i) => {
                  const value = (data as any)[def.key] as number | null;
                  const grade = gradeMetric(def.key, value);
                  const valueLabel =
                    value === null || value === undefined
                      ? '—'
                      : def.unit === '%'
                      ? formatPct(value)
                      : formatX(value);
                  return (
                    <MetricGauge
                      key={def.key}
                      index={i + 1}
                      label={def.label}
                      formula={def.formula}
                      target={def.target}
                      valueLabel={valueLabel}
                      fraction={gaugeFraction(def, value)}
                      thresholdFraction={thresholdFraction(def)}
                      grade={grade}
                    />
                  );
                })}
              </SectionCard>

              {/* FLAGS */}
              <SectionCard eyebrow="Playbook §5" title="Quality-of-Earnings Flags">
                <View style={styles.flagGrid}>
                  {flags.map((f, i) => (
                    <FlagCard key={f.id} flag={f} index={i + 1} />
                  ))}
                  {flags.length === 0 && <Text style={styles.helperText}>Not enough data to raise flags yet.</Text>}
                </View>
              </SectionCard>

              {/* VALUATION */}
              <SectionCard eyebrow="Playbook §4" title="Intrinsic Value & Margin of Safety">
                <Text style={styles.helperText}>V = EPS × (8.5 + 2g) × 4.4 ÷ Y  ·  Buy below S = V × 0.65</Text>
                {graham ? (
                  <>
                    <ValueBar price={data.price} marginOfSafetyPrice={graham.mos} intrinsicValue={graham.base} />
                    <View style={styles.scenarioRow}>
                      <ScenarioTile label="CONSERVATIVE" sub={`g 0-${Math.max(0, data.epsGrowthRatePct - 4).toFixed(0)}%`} value={graham.conservative} />
                      <ScenarioTile label="BASE" sub={`g ${data.epsGrowthRatePct.toFixed(0)}%`} value={graham.base} highlight />
                      <ScenarioTile label="OPTIMISTIC" sub={`g ${(data.epsGrowthRatePct + 4).toFixed(0)}%`} value={graham.optimistic} />
                    </View>
                    <Text style={styles.smallNote}>
                      EPS {formatUsd(data.eps)} · est. 5yr growth {data.epsGrowthRatePct.toFixed(1)}% · AAA yield {aaaYieldPct}% (Settings)
                    </Text>
                  </>
                ) : (
                  <Text style={styles.helperText}>No positive EPS available — Graham formula needs a positive trailing EPS.</Text>
                )}
              </SectionCard>

              {/* THESIS */}
              <SectionCard eyebrow="Fig.03 — Synthesis" title="Bull Case / Bear Case">
                <View style={styles.thesisCols}>
                  <View style={styles.thesisCol}>
                    <Text style={[styles.thesisHeader, { color: colors.pass }]}>THRUST</Text>
                    {thesis.bull.map((t, i) => (
                      <Text key={i} style={styles.thesisLine}>+ {t}</Text>
                    ))}
                    {assessment.extraBull ? <Text style={styles.thesisLine}>+ {assessment.extraBull}</Text> : null}
                  </View>
                  <View style={styles.thesisCol}>
                    <Text style={[styles.thesisHeader, { color: colors.fail }]}>DRAG</Text>
                    {thesis.bear.map((t, i) => (
                      <Text key={i} style={styles.thesisLine}>- {t}</Text>
                    ))}
                    {assessment.extraBear ? <Text style={styles.thesisLine}>- {assessment.extraBear}</Text> : null}
                  </View>
                </View>
                <TextInput
                  style={styles.thesisInput}
                  placeholder="Add your own bull point…"
                  placeholderTextColor={colors.textMuted}
                  value={assessment.extraBull}
                  onChangeText={(extraBull) => updateAssessment({ extraBull })}
                />
                <TextInput
                  style={styles.thesisInput}
                  placeholder="Add your own bear point…"
                  placeholderTextColor={colors.textMuted}
                  value={assessment.extraBear}
                  onChangeText={(extraBear) => updateAssessment({ extraBear })}
                />
              </SectionCard>

              {/* SYNTHESIS */}
              <SectionCard eyebrow="Analyst's Synthesis" title="Verdict">
                <TextInput
                  style={styles.headlineInput}
                  placeholder="One-line takeaway (e.g. Cheap and cash-rich, but cyclical.)"
                  placeholderTextColor={colors.textMuted}
                  value={assessment.headline}
                  onChangeText={(headline) => updateAssessment({ headline })}
                  multiline
                />
                <View style={styles.synthesisBadges}>
                  <Badge label={`QUALITY: ${quality}`} tone="teal" />
                  <Badge label={`MOAT: ${moatHeadline}`} tone="orange" />
                  <Badge label={`PRICE: ${priceTag}`} />
                </View>
              </SectionCard>

              <Text style={styles.disclaimer}>
                Informational and educational only — not investment, financial, tax, or legal advice. Figures are
                sourced from third-party data and may be delayed, estimated, or wrong. Playbook targets are
                guidelines, not rules, and vary by industry. Verify against primary filings before any decision.
              </Text>
            </>
          )}
        </ScrollView>
      </SafeAreaView>
    </ScreenBackground>
  );
}

const ScenarioTile: React.FC<{ label: string; sub: string; value: number; highlight?: boolean }> = ({ label, sub, value, highlight }) => (
  <View style={[styles.scenarioTile, highlight && styles.scenarioTileActive]}>
    <Text style={styles.scenarioLabel}>{label}</Text>
    <Text style={[styles.scenarioValue, highlight && { color: colors.teal }]}>{formatUsd(value)}</Text>
    <Text style={styles.scenarioSub}>{sub}</Text>
  </View>
);

const styles = StyleSheet.create({
  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing(5),
    paddingTop: spacing(2),
    paddingBottom: spacing(2),
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backText: { fontSize: 20, color: colors.textSecondary, marginTop: -2 },
  navTitle: { fontFamily: fonts.mono, fontSize: 13, letterSpacing: 1, color: colors.textSecondary },
  scroll: { paddingHorizontal: spacing(5), paddingBottom: spacing(12) },
  centerBox: { alignItems: 'center', paddingTop: spacing(16), paddingHorizontal: spacing(4) },
  loadingText: { fontFamily: fonts.bodyRegular, fontSize: 13, color: colors.textSecondary, marginTop: spacing(3) },
  errorTitle: { fontFamily: fonts.heading, fontSize: 17, color: colors.textPrimary, marginBottom: spacing(2) },
  errorBody: { fontFamily: fonts.bodyRegular, fontSize: 13, color: colors.textSecondary, textAlign: 'center', lineHeight: 19 },

  cover: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing(5),
    marginBottom: spacing(4),
  },
  eyebrow: { fontFamily: fonts.mono, fontSize: 9.5, letterSpacing: 1, color: colors.orange, marginBottom: 8 },
  companyName: { fontFamily: fonts.display, fontSize: 24, color: colors.textPrimary, marginBottom: 8 },
  tickerRow: { flexDirection: 'row', gap: 8, marginBottom: spacing(4) },
  priceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: spacing(3) },
  price: { fontFamily: fonts.display, fontSize: 30, color: colors.textPrimary },
  changePct: { fontFamily: fonts.monoBold, fontSize: 13, marginTop: 2 },
  mktCapLabel: { fontFamily: fonts.mono, fontSize: 10, color: colors.textMuted, letterSpacing: 1 },
  mktCapValue: { fontFamily: fonts.heading, fontSize: 18, color: colors.textPrimary, marginTop: 2 },
  rangeWrap: { marginBottom: spacing(4) },
  rangeTrack: { height: 4, borderRadius: 2, backgroundColor: colors.gaugeTrack, position: 'relative', marginBottom: 8 },
  rangeDot: { position: 'absolute', top: -4, width: 12, height: 12, borderRadius: 6, backgroundColor: colors.teal, marginLeft: -6 },
  rangeLabels: { flexDirection: 'row', justifyContent: 'space-between' },
  rangeText: { fontFamily: fonts.mono, fontSize: 9.5, color: colors.textMuted },
  ratingBlock: {},
  fieldLabel: { fontFamily: fonts.mono, fontSize: 10, letterSpacing: 1, color: colors.textMuted, marginBottom: 6 },

  tileGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  paragraph: { fontFamily: fonts.bodyRegular, fontSize: 13, lineHeight: 20, color: colors.textSecondary },
  helperText: { fontFamily: fonts.bodyRegular, fontSize: 11.5, color: colors.textMuted, marginBottom: spacing(2) },

  flagGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },

  scenarioRow: { flexDirection: 'row', gap: 8, marginTop: spacing(2) },
  scenarioTile: {
    flex: 1,
    backgroundColor: colors.cardAlt,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing(3),
    alignItems: 'center',
  },
  scenarioTileActive: { borderColor: colors.teal },
  scenarioLabel: { fontFamily: fonts.mono, fontSize: 9, color: colors.textMuted, letterSpacing: 0.5 },
  scenarioValue: { fontFamily: fonts.heading, fontSize: 16, color: colors.textPrimary, marginTop: 4 },
  scenarioSub: { fontFamily: fonts.mono, fontSize: 9, color: colors.textMuted, marginTop: 2 },
  smallNote: { fontFamily: fonts.bodyRegular, fontSize: 11, color: colors.textMuted, marginTop: spacing(3) },

  thesisCols: { flexDirection: 'row', gap: 12 },
  thesisCol: { flex: 1 },
  thesisHeader: { fontFamily: fonts.mono, fontSize: 11, letterSpacing: 1, marginBottom: 6 },
  thesisLine: { fontFamily: fonts.bodyRegular, fontSize: 12, lineHeight: 18, color: colors.textSecondary, marginBottom: 4 },
  thesisInput: {
    fontFamily: fonts.bodyRegular,
    fontSize: 12,
    color: colors.textPrimary,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    marginTop: spacing(2),
    backgroundColor: colors.cardAlt,
  },
  headlineInput: {
    fontFamily: fonts.heading,
    fontSize: 15,
    color: colors.textPrimary,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: spacing(3),
    backgroundColor: colors.cardAlt,
    marginBottom: spacing(3),
  },
  synthesisBadges: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },

  disclaimer: {
    fontFamily: fonts.bodyRegular,
    fontSize: 10.5,
    lineHeight: 15,
    color: colors.textMuted,
    marginTop: spacing(2),
  },
});
